name: Post Changelog to Discord

on:
  push:
    branches:
      - main # Important: Change to your default branch if not 'main'
    paths:
      - 'CHANGELOG.md' # Important: Change to the correct path of your file

jobs:
  post-to-discord:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code to access the file
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Send the changelog file as an attachment to Discord
      - name: Send Changelog to Discord
        run: |
          curl -X POST \
          -F "payload_json={\"content\": \"🚀 **New Changelog Update!** See attached file.\", \"username\": \"DevRight Studios Changelog\"}" \
          -F "file1=@CHANGELOG.md" \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
